* src/include/getopt.h, src/libs/libgroff/{getopt.c, getopt1.c}: Updated to latest version of libc.
* configure.ac: Don't create subdirectories before AC_CONFIG_FILES.
Autoconf 2.50 and newer can handle this.
* configure: Regenerated.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4719,7 +4719,6 @@ fi
 echo "$as_me:4719: result: $tmac_wrap" >&5
 echo "${ECHO_T}$tmac_wrap" >&6
 
-$srcdir/mkinstalldirs src/xditview
 ac_config_files="$ac_config_files stamp-h"
 
 ac_config_files="$ac_config_files Makefile src/xditview/Imakefile"
@@ -4803,7 +4802,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:4806: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:4805: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -4976,7 +4975,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:4979: error: ambiguous option: $1
+    { { echo "$as_me:4978: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -5001,12 +5000,12 @@ Try \`$0 --help' for more information." >&2;}
   'src/include/config.h' ) CONFIG_HEADERS="$CONFIG_HEADERS src/include/config.h:src/include/config.hin" ;;
 
   # This is an error.
-  -*) { { echo "$as_me:5004: error: unrecognized option: $1
+  -*) { { echo "$as_me:5003: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
    { (exit 1); exit 1; }; } ;;
-  *) { { echo "$as_me:5009: error: invalid argument: $1" >&5
+  *) { { echo "$as_me:5008: error: invalid argument: $1" >&5
 echo "$as_me: error: invalid argument: $1" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -5248,7 +5247,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:5251: creating $ac_file" >&5
+    { echo "$as_me:5250: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -5266,7 +5265,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:5269: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:5268: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -5279,7 +5278,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:5282: error: cannot find input file: $f" >&5
+           { { echo "$as_me:5281: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -5344,7 +5343,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:5347: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:5346: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -5355,7 +5354,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:5358: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:5357: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -5368,7 +5367,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:5371: error: cannot find input file: $f" >&5
+           { { echo "$as_me:5370: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -5485,7 +5484,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:5488: $ac_file is unchanged" >&5
+      { echo "$as_me:5487: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
