Don't produce HTML files if utility programs are missing.
* Makefile.in (make_html, make_install_html): New variables.
(MDEFINES): Updated.

* aclocal.m4 (GROFF_HTML_PROGRAMS): New function to test for HTML
utility programs.
* configure.ac: Use it.
* configure: Regenerated.

* doc/Makefile.sub (PROCESSEDEXAMPLEFILES): Move webpage.html to...
(HTMLEXAMPLESFILES): This new variable.
(EXAMPLESIMAGEFILES): Renamed to...
(HTMLEXAMPLEIMAGEFILES): This.
(CLEANADD): Add HTMLEXAMPLEFILES.
(all): Use `make_html'.
(html): New target.
(install_data): Use `make_install_html'.
Move html stuff to...
(install_html): This new target.
(uninstall_sub): Updated.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5044,6 +5044,191 @@ fi
 echo "$as_me:5044: result: $tmac_wrap" >&5
 echo "${ECHO_T}$tmac_wrap" >&6
 
+make_html=html
+make_install_html=install_html
+# Extract the first word of "pnmcut", so it can be a program name with args.
+set dummy pnmcut; ac_word=$2
+echo "$as_me:5051: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_pnmcut+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$pnmcut"; then
+  ac_cv_prog_pnmcut="$pnmcut" # Let the user override the test.
+else
+  ac_save_IFS=$IFS; IFS=$ac_path_separator
+ac_dummy="$PATH"
+for ac_dir in $ac_dummy; do
+  IFS=$ac_save_IFS
+  test -z "$ac_dir" && ac_dir=.
+  $as_executable_p "$ac_dir/$ac_word" || continue
+ac_cv_prog_pnmcut="found"
+echo "$as_me:5066: found $ac_dir/$ac_word" >&5
+break
+done
+
+  test -z "$ac_cv_prog_pnmcut" && ac_cv_prog_pnmcut="missing"
+fi
+fi
+pnmcut=$ac_cv_prog_pnmcut
+if test -n "$pnmcut"; then
+  echo "$as_me:5075: result: $pnmcut" >&5
+echo "${ECHO_T}$pnmcut" >&6
+else
+  echo "$as_me:5078: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+# Extract the first word of "pnmcrop", so it can be a program name with args.
+set dummy pnmcrop; ac_word=$2
+echo "$as_me:5084: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_pnmcrop+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$pnmcrop"; then
+  ac_cv_prog_pnmcrop="$pnmcrop" # Let the user override the test.
+else
+  ac_save_IFS=$IFS; IFS=$ac_path_separator
+ac_dummy="$PATH"
+for ac_dir in $ac_dummy; do
+  IFS=$ac_save_IFS
+  test -z "$ac_dir" && ac_dir=.
+  $as_executable_p "$ac_dir/$ac_word" || continue
+ac_cv_prog_pnmcrop="found"
+echo "$as_me:5099: found $ac_dir/$ac_word" >&5
+break
+done
+
+  test -z "$ac_cv_prog_pnmcrop" && ac_cv_prog_pnmcrop="missing"
+fi
+fi
+pnmcrop=$ac_cv_prog_pnmcrop
+if test -n "$pnmcrop"; then
+  echo "$as_me:5108: result: $pnmcrop" >&5
+echo "${ECHO_T}$pnmcrop" >&6
+else
+  echo "$as_me:5111: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+# Extract the first word of "pnmtopng", so it can be a program name with args.
+set dummy pnmtopng; ac_word=$2
+echo "$as_me:5117: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_pnmtopng+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$pnmtopng"; then
+  ac_cv_prog_pnmtopng="$pnmtopng" # Let the user override the test.
+else
+  ac_save_IFS=$IFS; IFS=$ac_path_separator
+ac_dummy="$PATH"
+for ac_dir in $ac_dummy; do
+  IFS=$ac_save_IFS
+  test -z "$ac_dir" && ac_dir=.
+  $as_executable_p "$ac_dir/$ac_word" || continue
+ac_cv_prog_pnmtopng="found"
+echo "$as_me:5132: found $ac_dir/$ac_word" >&5
+break
+done
+
+  test -z "$ac_cv_prog_pnmtopng" && ac_cv_prog_pnmtopng="missing"
+fi
+fi
+pnmtopng=$ac_cv_prog_pnmtopng
+if test -n "$pnmtopng"; then
+  echo "$as_me:5141: result: $pnmtopng" >&5
+echo "${ECHO_T}$pnmtopng" >&6
+else
+  echo "$as_me:5144: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+# Extract the first word of "gs gsos2", so it can be a program name with args.
+set dummy gs gsos2; ac_word=$2
+echo "$as_me:5150: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_gs+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$gs"; then
+  ac_cv_prog_gs="$gs" # Let the user override the test.
+else
+  ac_save_IFS=$IFS; IFS=$ac_path_separator
+ac_dummy="$PATH"
+for ac_dir in $ac_dummy; do
+  IFS=$ac_save_IFS
+  test -z "$ac_dir" && ac_dir=.
+  $as_executable_p "$ac_dir/$ac_word" || continue
+ac_cv_prog_gs="found"
+echo "$as_me:5165: found $ac_dir/$ac_word" >&5
+break
+done
+
+  test -z "$ac_cv_prog_gs" && ac_cv_prog_gs="missing"
+fi
+fi
+gs=$ac_cv_prog_gs
+if test -n "$gs"; then
+  echo "$as_me:5174: result: $gs" >&5
+echo "${ECHO_T}$gs" >&6
+else
+  echo "$as_me:5177: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+# Extract the first word of "psselect", so it can be a program name with args.
+set dummy psselect; ac_word=$2
+echo "$as_me:5183: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_psselect+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$psselect"; then
+  ac_cv_prog_psselect="$psselect" # Let the user override the test.
+else
+  ac_save_IFS=$IFS; IFS=$ac_path_separator
+ac_dummy="$PATH"
+for ac_dir in $ac_dummy; do
+  IFS=$ac_save_IFS
+  test -z "$ac_dir" && ac_dir=.
+  $as_executable_p "$ac_dir/$ac_word" || continue
+ac_cv_prog_psselect="found"
+echo "$as_me:5198: found $ac_dir/$ac_word" >&5
+break
+done
+
+  test -z "$ac_cv_prog_psselect" && ac_cv_prog_psselect="missing"
+fi
+fi
+psselect=$ac_cv_prog_psselect
+if test -n "$psselect"; then
+  echo "$as_me:5207: result: $psselect" >&5
+echo "${ECHO_T}$psselect" >&6
+else
+  echo "$as_me:5210: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+case "x$pnmcut$pnmcrop$pnmtopng$gs$psselect" in
+*missing*)
+	make_html=
+	make_install_html=
+	{ echo "$as_me:5218: WARNING:
+
+  Since one or more of the above five programs can't be found in the path,
+  the HTML backend of groff (grohtml) won't work properly.  Consequently,
+  no documentation in HTML format is built and installed.
+" >&5
+echo "$as_me: WARNING:
+
+  Since one or more of the above five programs can't be found in the path,
+  the HTML backend of groff (grohtml) won't work properly.  Consequently,
+  no documentation in HTML format is built and installed.
+" >&2;} ;;
+esac
+
 ac_config_files="$ac_config_files stamp-h"
 
 ac_config_files="$ac_config_files Makefile doc/Makefile src/xditview/Imakefile"
@@ -5127,7 +5312,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:5130: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:5315: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -5300,7 +5485,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:5303: error: ambiguous option: $1
+    { { echo "$as_me:5488: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -5319,7 +5504,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:5322: error: unrecognized option: $1
+  -*) { { echo "$as_me:5507: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -5359,7 +5544,7 @@ do
   "doc/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/Makefile" ;;
   "src/xditview/Imakefile" ) CONFIG_FILES="$CONFIG_FILES src/xditview/Imakefile" ;;
   "src/include/config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS src/include/config.h:src/include/config.hin" ;;
-  *) { { echo "$as_me:5362: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:5547: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -5476,6 +5661,13 @@ s,@PAGE@,$PAGE,;t t
 s,@g@,$g,;t t
 s,@sys_tmac_prefix@,$sys_tmac_prefix,;t t
 s,@tmac_wrap@,$tmac_wrap,;t t
+s,@pnmcut@,$pnmcut,;t t
+s,@pnmcrop@,$pnmcrop,;t t
+s,@pnmtopng@,$pnmtopng,;t t
+s,@gs@,$gs,;t t
+s,@psselect@,$psselect,;t t
+s,@make_html@,$make_html,;t t
+s,@make_install_html@,$make_install_html,;t t
 CEOF
 
 EOF
@@ -5590,7 +5782,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:5593: creating $ac_file" >&5
+    { echo "$as_me:5785: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -5608,7 +5800,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:5611: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:5803: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -5621,7 +5813,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:5624: error: cannot find input file: $f" >&5
+           { { echo "$as_me:5816: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -5686,7 +5878,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:5689: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:5881: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -5697,7 +5889,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:5700: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:5892: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -5710,7 +5902,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:5713: error: cannot find input file: $f" >&5
+           { { echo "$as_me:5905: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -5827,7 +6019,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:5830: $ac_file is unchanged" >&5
+      { echo "$as_me:6022: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
@@ -5894,7 +6086,7 @@ if test "$no_create" != yes; then
   $ac_cs_success || { (exit 1); exit 1; }
 fi
 
-{ echo "$as_me:5897:
+{ echo "$as_me:6089:
 
   Configuration completed.
 
